#!/bin/sh /etc/rc.common
# Original Omega_Garage Boot Script Created by James Harding
# https://github.com/JimJamUrCode for more...

START=99
STOP=1

start() {
        echo start >> /tmp/output.txt
	git clone --progress https://github.com/jedwood/omega_doorlock.git /tmp/omega_doorlock 2> /root/gitoutput.log
	node /tmp/omega_doorlock/omega_doorlockServer.js
}

stop() {
        echo stop
        # commands to kill application
        killall node
}
